[package]
name = "bevy3Danimation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.18.1", features = ["hotpatching","jpeg", "png","tga","bmp","hdr"] }
crossbeam-channel = "0.5.15"
PMXUtil = "0.9.0"
bevy_panorbit_camera = "0.34.0"
vmd_parser = "0.1.0"
bevy-inspector-egui = "0.36"
[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
