[package]
name = "bevy3Danimation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.19.1", features = ["jpeg", "png", "tga", "bmp", "hdr"] }
PMXUtil = "0.9.0"
bevy_panorbit_camera = "0.35.1"
vmd_parser = "0.1.0"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.5"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
